module.exports = {
  PORT: process.env.PORT,
  COOKIE_KEY: process.env.COOKIE_KEY,
  SPOTIFY_CLIENTID: process.env.SPOTIFY_CLIENTID,
  SPOTIFY_CLIENTSECRET: process.env.SPOTIFY_CLIENTSECRET,
  SPOTIFY_CALLBACKURL: process.env.SPOTIFY_CALLBACKURL,
  BASE_URL: process.env.BASE_URL,
  API_BASE_URL: process.env.API_BASE_URL,
};
